### ISSUE TITLE
Stuck on seed 42

### ISSUE THREAD

**Issue by chinaexpert1A** [DN6/giffusion#12] opened 2023-01-15 16:40 UTC
something is wrong. changing the seed doesn't change the output.
I'm not sure what Use Fixed Latent Init means, but it is False

**Comment by DN6** [comment] 2023-01-15 17:09
Hi @chinaexpert1A. I think I know what the issue is. I'll push up a fix by the end of the day.

**Comment by chinaexpert1A** [comment] 2023-01-15 20:33
Great. I would love to see you continue with this project, building in some of the features of Deforum if it appeals to you. Your approach preserves color where the previous frame as init approach tends towards saturation/color problems.

**Comment by DN6** [comment] 2023-01-16 08:18
@chinaexpert1A Should be fixed. Can you try it out and confirm?

**Closed** 2023-01-25 16:15 UTC
